// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_stag_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcjlVxHN29F9qQkgpRx4Rbb--Yq_uVmXM',
    appId: '1:82682289256:android:162f15484eab426ec0afdd',
    messagingSenderId: '82682289256',
    projectId: 'miittiappdev',
    storageBucket: 'miittiappdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpeQuf8IaR7RYkwI2WnOD_zmCQlkuW0SY',
    appId: '1:82682289256:ios:4a0550a73f7caa77c0afdd',
    messagingSenderId: '82682289256',
    projectId: 'miittiappdev',
    storageBucket: 'miittiappdev.appspot.com',
    androidClientId: '82682289256-arit3pns7ovnhmhpaq5mo4n0ir9j0vog.apps.googleusercontent.com',
    iosClientId: '82682289256-d3lb47ujpluicf2qujoel9fc5lncbpn5.apps.googleusercontent.com',
    iosBundleId: 'com.miittisoftwareoy.miittiApp.dev',
  );

}