// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_prod_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6O5kWfv0k-mp19IoOv7FufA4TqWaprkA',
    appId: '1:261026197907:android:09668553c4cfb03265f866',
    messagingSenderId: '261026197907',
    projectId: 'miitti-app',
    storageBucket: 'miitti-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEA0TwBaMDTHGMyYCeibh1NafS3U7clSY',
    appId: '1:261026197907:ios:6ebb8041e71b845a65f866',
    messagingSenderId: '261026197907',
    projectId: 'miitti-app',
    storageBucket: 'miitti-app.appspot.com',
    androidClientId: '261026197907-7fus2crid7jv6fi04qp8tsle71fc4pbp.apps.googleusercontent.com',
    iosClientId: '261026197907-i64t5euqb0bglan58fonrbgtu6qh53ik.apps.googleusercontent.com',
    iosBundleId: 'com.miittisoftwareoy.miittiApp',
  );

}