// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_stag_configuration.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC_D5lV3Eve7_4JrVlyM7cknL08LgV148',
    appId: '1:377453260995:android:96c8db20dbb3c1a3a63276',
    messagingSenderId: '377453260995',
    projectId: 'miittiappstage',
    storageBucket: 'miittiappstage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNO-JekPGUQ-0K5eyfq3fgK_UBsE7V68',
    appId: '1:377453260995:ios:13bdc56602c749a7a63276',
    messagingSenderId: '377453260995',
    projectId: 'miittiappstage',
    storageBucket: 'miittiappstage.appspot.com',
    androidClientId: '377453260995-eqtoj53bv2s1bnk62sptb9cmlr0ga6em.apps.googleusercontent.com',
    iosClientId: '377453260995-c3t82thsa88u8g7gd845v6n8b3vn9vq9.apps.googleusercontent.com',
    iosBundleId: 'com.miittisoftwareoy.miittiApp.stg',
  );

}